AllCops:
  SuggestExtensions: false
  NewCops: disable

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 160

Style/AsciiComments:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false
