FROM icyleafcn/crystal:latest

ADD . /app
WORKDIR /app

RUN apk add --update --no-cache gcc openssl-dev git bash openssh-client && \
    chmod +x docker-entrypoint.sh && mv docker-entrypoint.sh /docker-entrypoint.sh && \
    shards build --production && \
    ldd bin/hpr | tr -s '[:blank:]' '\n' | grep '^/' | xargs -I % sh -c 'mkdir -p $(dirname deps%); cp % deps%'

VOLUME ["/app/config", "/app/repositories"]

EXPOSE 8848/tcp

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["hpr:init"]
