#!/usr/bin/with-contenv sh

HPR_SSH_PATH=/app/.ssh

cleanup_workspace() {
  mkdir -p /app/repositories
  mkdir -p /app/.ssh
}

generate_ssh_key() {
  if ! [ -f "${HPR_SSH_PATH}/id_rsa" ]; then
    echo "Generating public/private rsa key pair ..."
    ssh-keygen -q -t rsa -N "" -f "${HPR_SSH_PATH}/id_rsa" -C "hpr@docker"
  fi

  echo
  echo "SSH PUBLIC KEY:"
  echo "##################################################################"
  echo `cat ${HPR_SSH_PATH}/id_rsa.pub`
  echo "##################################################################"
  echo

  ln -sf ${HPR_SSH_PATH} /root/.ssh
}

config_ssh_config() {
  HPR_SSH_HOST=${HPR_SSH_HOST:-*}
  HPR_SSH_PORT=${HPR_SSH_PORT:-22}

  if ! [ grep -q "$HPR_SSH_HOST" "/app/.ssh/config" ]; then
    echo "Configuring ssh config ..."
    echo "Host ${HPR_SSH_HOST}" > ${HPR_SSH_PATH}/config
    echo "    HostName ${HPR_SSH_HOST}" >> ${HPR_SSH_PATH}/config
    echo "    Port ${HPR_SSH_PORT}" >> ${HPR_SSH_PATH}/config
    echo "    StrictHostKeyChecking no" >> ${HPR_SSH_PATH}/config
  fi
}

cleanup_workspace
generate_ssh_key
config_ssh_config
