#!/usr/bin/with-contenv sh

# remove unused docker rootfs
rm -rf /app/docker

# create repositores directory
mkdir -p /app/repositories

# create logs directory
mkdir -p /app/logs

# create database directory
mkdir -p /app/database

# load config file
echo "Load config file"
if ! [ -f "/app/config/hpr.yml" ]; then
  echo "-- no found hpr.yml config file, copy from template."
  cp /app/config/hpr.example.yml /app/config/hpr.yml
else
  echo "-- using exists /app/config/hpr.yml"
fi
# init database
echo "Load databae file"
/app/bin/rake -f /app/Rakefile db:setup
