#!/usr/bin/with-contenv sh

# Config redis server
REDIS_URL=tcp://localhost:6379
REDIS_PROVIDER=REDIS_URL

# create logs directory
mkdir -p /app/logs

echo "** Starting Hpr.."
cd /app
exec hpr server 2>&1 | tee -a /app/logs/hpr.log
